name: qertsa
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  nb_utils: ^6.1.2
  google_fonts: ^6.1.0
  country_code_picker: ^3.0.0
  pinput: ^3.0.1
  font_awesome_flutter: ^10.6.0
  provider: ^6.1.1
  image_picker: ^1.0.7
  audioplayers: ^5.2.1
  record: ^5.0.4
  path_provider: ^2.1.2
  geolocator: ^10.1.0
  contacts_service: ^0.6.3
  permission_handler: ^11.2.0
#  agora_rtc_engine: ^6.2.6
  agora_uikit: ^1.3.8
  flutter_local_notifications: ^16.3.2
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.16.0
  firebase_messaging: ^14.9.1
  firebase_storage: ^11.7.1
  app_settings: ^5.1.1
  fluttertoast: ^8.2.4
  another_flushbar: ^1.12.30
  http: ^1.2.1
  fast_contacts: ^3.1.3
  intl: ^0.19.0
  bouncing_widget: ^2.0.0
  loading_animation_widget: ^1.2.1
  multi_dropdown: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
#  flutter_app_name: ^0.1.1
#flutter_app_name:
#  name: "Qertsa"
#  flutter_launcher_icons: ^0.13.1
#flutter_launcher_icons:
#  android: "launcher_icon"
#  ios: true
#  image_path: "assets/app_icon.png"
#  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/recording/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
