// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9xpHDflIPfaIKWC1iCUF_Fq07gqmT6P0',
    appId: '1:992876789713:web:972d2af11831efd5f92af0',
    messagingSenderId: '992876789713',
    projectId: 'qertsachat',
    authDomain: 'qertsachat.firebaseapp.com',
    storageBucket: 'qertsachat.appspot.com',
    measurementId: 'G-FVWTFN7F67',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLWOFmha3502TXMwAZzcMrQVOrBn4CX2Q',
    appId: '1:992876789713:android:93f73f3771288322f92af0',
    messagingSenderId: '992876789713',
    projectId: 'qertsachat',
    storageBucket: 'qertsachat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEEaQrhx4lBf64EDFtaD2Q1tJbQcYwA4g',
    appId: '1:992876789713:ios:d4bffb6e61c2d675f92af0',
    messagingSenderId: '992876789713',
    projectId: 'qertsachat',
    storageBucket: 'qertsachat.appspot.com',
    iosBundleId: 'com.example.qertsa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEEaQrhx4lBf64EDFtaD2Q1tJbQcYwA4g',
    appId: '1:992876789713:ios:9b66f685389da9fcf92af0',
    messagingSenderId: '992876789713',
    projectId: 'qertsachat',
    storageBucket: 'qertsachat.appspot.com',
    iosBundleId: 'com.example.qertsa.RunnerTests',
  );
}
